language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
before_install:
  - perlbrew -f install-cpanm
  - cpanm -n Devel::Cover::Report::Coveralls
install: cpanm --with-develop --installdeps --notest .
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
