language: perl
perl:
  - "5.16"
  - "5.14"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls DBD::SQLite Test::mysqld
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
